### ISSUE TITLE
wrong url

### ISSUE THREAD

**Issue by SlayerOrnstein** [matanlurey/din#15]
the link next to "dart api for discord" should have be https://pub.dartlang.org/packages/din

**Comment by JacquezHanzel** [comment]
Hello, how did you come up with the username Darklightning167?

**Comment by matanlurey** [comment]
@Darklightning167 done, thanks!

**Comment by SlayerOrnstein** [comment]
@JacquezHanzel old PSN name coming up with a username for everything gets kind of annoying to keep track of
@matanlurey no problem
